services:
  rasa:
    image: rasa/rasa:3.1.0
    container_name: rasa_server
    volumes:
      - ./rasa:/app

    command: run --enable-api --cors "*" --debug

    depends_on:
      - actions

  actions:
    build: ./actions
    container_name: rasa_actions
    volumes:
      - ./actions:/app

  web:
    build: ./django
    container_name: django_web
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - db_volume:/app/db
    expose:
      - "8000"
    depends_on:
      - rasa

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
  db_volume:
