services:
  web:
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env
    volumes:
      - ./django:/app
      # - ./django/db:/app/db
    ports:
      - "8000:8000"
    depends_on:
      - rasa
      - db

  rasa:
    command: run --enable-api --cors "*" --debug
    volumes:
      - ./rasa:/app

  actions:
    volumes:
      - ./actions:/app
