services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

    # ports:
    #   - "5432:5432"

  rasa:
    image: rasa/rasa:3.1.0
    container_name: rasa_server
    volumes:
      - ./rasa:/app

    command: run --enable-api --cors "*" --debug
    depends_on:
      - actions
    networks:
      - backend
    restart: unless-stopped

  actions:
    build: ./actions
    container_name: rasa_actions
    volumes:
      - ./actions:/app
    networks:
      - backend
    restart: unless-stopped

  web:
    build: ./django
    container_name: django_web
    env_file:
      - .env
    volumes:
      - ./django:/app
      - static_volume:/app/staticfiles
      # - db_volume:/app/db
    expose:
      - "8000"
    command: >
      sh -c "python manage.py collectstatic --noinput &&
             python manage.py migrate &&
             gunicorn --bind 0.0.0.0:8000 --workers 3 config.wsgi:application"
    depends_on:
      db:
        condition: service_healthy
      rasa:
        condition: service_started
    networks:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
    depends_on:
      - web
    networks:
      - backend
    restart: unless-stopped

volumes:
  static_volume:
  postgres_data:
  # db_volume:

networks:
  backend:
