services:
  rasa:
    image: rasa/rasa:3.1.0
    container_name: rasa_server
    volumes:
      - ./rasa:/app

    ports:
      - "5005:5005"
    command: run --enable-api --cors "*" --debug

    depends_on:
      - actions

  actions:
    build: ./actions
    container_name: rasa_actions
    ports:
      - "5055:5055"

  web:
    build: ./django
    container_name: django_web
    env_file:
      - .env
    volumes:
      - ./django:/app
    ports:
      - "8000:8000"
    depends_on:
      - rasa
