services:
  rasa:
    image: rasa/rasa:3.1.0
    container_name: rasa_server
    volumes:
      - ./rasa:/app

    # ports:
    #   - "5005:5005"
    command: run --enable-api --cors "*" --debug

    depends_on:
      - actions

  actions:
    build: ./actions
    container_name: rasa_actions
    volumes:
      - ./actions:/app
    # ports:
    #   - "5055:5055"

  web:
    build: ./django
    container_name: django_web
    env_file:
      - .env
    volumes:
      # - ./django:/app
      - static_volume:/app/staticfiles
    expose:
      - "8000"
    # ports:
    #   - "8000:8000"
    depends_on:
      - rasa

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  static_volume:
